//
//  LocationDataSource.swift
//  Week7 Homework
//
//  Created by Hanna Chen on 3/6/17.
//  Copyright © 2017 Rethink Canada. All rights reserved.
//

import Foundation
import UIKit

class LocationDataSource {
    var locations: [Location]
    
    init() {
        locations = []
        let australia = Location(name: "Australia", image: #imageLiteral(resourceName: "australia"), description: "Australia, a federation of six states and two territories, is one of the world’s great economic and migration success stories. Australia is a unique, modern and dynamic trading nation of 22 million people with an ancient indigenous history, and a European cultural background. \n\rAustralia’s coastline stretches almost 50,000 kilometres and is linked by over 10,000 beaches, more than any other country in the world. More than 85 per cent of Australians lives within 50 kilometres of the coast, making it an integral part of our laid-back lifestyle.")
        locations.append(australia)
        
        let canada = Location(name: "Canada", image: #imageLiteral(resourceName: "canada"), description: "Canada is the second largest country in the world and a nation of great ethnic and cultural diversity.\n\rInitially populated by various First Nation tribes and then colonized by the French and British, Canada is today a cultural mosaic made up of people who have come from all around the world.\n\rFew countries can compare with the natural beauty, geographic diversity and wildlife of Canada. Bordered by the Atlantic, Pacific and Arctic Oceans, Canada’s ever-changing topography ranges from the dizzying heights of the Rocky Mountains to vast boreal forests, endless prairies, desert and rainforest regions. Added to the extraordinary natural beauty are the vibrant, cosmopolitan cities where most of the population lives.")
        locations.append(canada)
        
        let china = Location(name: "China", image: #imageLiteral(resourceName: "china"), description: "Splendidly diverse in its geographic, ethnic, culinary and social make-up, China is a nation on the march. Developing at a rate unmatched in human history, already huge cities are adding sprawling suburbs and cutting-edge architecture on a day-by-day basis, even as an ever-expanding web of high-speed rail ties the country together. Nevertheless, this apparent modernity is based on a civilization that has remained intact, continually recycling itself, for over four millennia. Chinese script reached perfection during the Han dynasty (220 BC–220 AD), and those stone lions standing sentinel outside sleek new skyscrapers first appeared as temple guardians over three thousand years ago. Indeed, it is the tension and contrasts between change and continuity that make modern China so fascinating.")
        locations.append(china)
        
        let france = Location(name: "France", image: #imageLiteral(resourceName: "france"), description: "The sheer physical diversity of France would be hard to exhaust in a lifetime of visits. Places to visit in France range from the fretted coasts of Brittany and the limestone hills of Provence to the canyons of the Pyrenees and the half-moon bays of Corsica, and from the lushly wooded valleys of the Dordogne and the gentle meadows of the Loire valley to the glaciated peaks of the Alps. Each region looks and feels different, has its own style of architecture, its own characteristic food and often its own dialect. Though the French word pays is the term for a whole country, people frequently refer to their own region as mon pays – my country – and this strong sense of regional identity has persisted despite centuries of centralizing governments, from Louis XIV to de Gaulle.")
        locations.append(france)
        
        let germany = Location(name: "Germany", image: #imageLiteral(resourceName: "germany"), description: "Though it remains far less well known or understood by outsiders than some of its neighbours, since reunification Germany has at last gained a higher profile as a place to visit, thanks partly to the remarkable resurgence of Berlin, one of the most fascinating and exciting cities in Europe. But the appeal of the reunified Germany is not limited to the capital. The 2006 football World Cup was something of a turning point, both with regards to Germany’s image abroad and to its own self-image, rehabilitating the idea of German patriotism for the first time since the war. When football fans descended on cities all over the country, they discovered a friendly, multiethnic and multicultural nation that was, for the most part, at ease with itself, finally happy to fly its own flag in a harmless display of national pride.")
        locations.append(germany)
        
        let iceland = Location(name: "Iceland", image: #imageLiteral(resourceName: "iceland"), description: "Resting on the edge of the Arctic Circle and sitting atop one of the world’s most volcanically active hot spots, Iceland is an inspiring mix of magisterial glaciers, bubbling hot springs and rugged fjords, where activities such as hiking under the Midnight Sun are complemented by healthy doses of history and literature.\n\rIceland is a place where nature reigns supreme. Aside from the modern and cosmopolitan capital, Reykjavík, population centres are small, with diminutive towns, fishing villages, farms and minute hamlets clustered along the coastal fringes. The Interior, meanwhile, remains totally uninhabited and unmarked by humanity: a starkly beautiful wilderness of ice fields, windswept upland plateaux, infertile lava and ash deserts and the frigid vastness of Vatnajökull, Europe’s largest glacier. Iceland’s location on the Mid-Atlantic ridge also gives it one of the most volcanically active landscapes on Earth, peppered with everything from naturally occurring hot springs, scaldingly hot bubbling mud pools and noisy steam vents to a string of unpredictably violent volcanoes, which have regularly devastated huge parts of the country. The latest events came in 2010, when Eyjafjallajökull erupted and caused havoc across Europe; and in 2015, when the eruption at Holuhraun created a huge new lavafield.")
        locations.append(iceland)
        
        let italy = Location(name: "Italy", image: #imageLiteral(resourceName: "italy"), description: "Ask an Italian where in the world they would most like to live, and the odds are that they will say “right here”. Indeed, most people – not just Italians – have raved about Italy since tourism began, and to be honest the country really does have it all: one of the most diverse and beautiful landscapes in Europe; the world’s greatest hoard of art treasures (many on display in fittingly spectacular cities and buildings); a climate that is on the whole benign; and, most important of all for many, a delicious and authentic national cuisine. The country is not perfect – its historic cities have often been marred by development, and beyond the showpiece sights the infrastructure is visibly straining – but for its places to visit, many of the old clichés still ring true; once you’ve visited, you may never want to travel anywhere else.")
        locations.append(italy)
        
        let japan = Location(name: "Japan", image: #imageLiteral(resourceName: "japan"), description: "Anyone who’s ever eaten sushi, read manga, or sipped sake may feel they know something about this slinky archipelago of some 6800 volcanic islands. And yet, from the moment of arrival in Japan, it’s almost as if you’ve touched down on another planet. Prepare to be pleasantly disorientated as you negotiate this fascinating land where ancient gods, customs and craftsmanship are mixed up with cutting edge modern technology, futuristic fashions and up-to-the-second style.\n\rHigh-speed trains whisk you from one end of the country to another with awe-inspiring punctuality. In the suburbs of a sprawling metropolis, you can catch sight of a farmer tending his paddy field, then turn the corner and find yourself next to a neon-festooned (video) games parlour. One day you could be picking through fashions in a boutique designed by an award-winning architect, the next relaxing in an outdoor hot-spring pool, watching cherry blossom or snowflakes fall, depending on the season.")
        locations.append(japan)
        
        let madagascar = Location(name: "Madagascar", image: #imageLiteral(resourceName: "madagascar"), description: "Madagascar has no parallel: an extraordinary storehouse of natural and cultural riches, it makes experienced travellers question what it means to say a country is unique. Separated from Africa and Asia at the time of the dinosaurs, animal life here has evolved in a startling myriad of forms, creating a profusion of endemic species found nowhere else on earth. Humans were not part of that process: they first colonized this huge island less than 2000 years ago, when it was a primal Eden, inhabited only by its bizarre and marvellous zoological cornucopia. As biologists discover more and more about this remarkable place, calling it the eighth continent barely does it justice: second planet seems more appropriate.")
        locations.append(madagascar)
        
        let peru = Location(name: "Peru", image: #imageLiteral(resourceName: "peru"), description: "From exotic jungle to coastal desert via the breathtaking peaks of the Andes, Peru’s staggering variety of places to visit means the potential for adventure is boundless. Whether you want to trek the hallowed Inca Trail, drink pisco sours in a sleepy colonial town, swim with pink dolphins or paddle your way down the Amazon in a dugout canoe – or all of the above – this is a country that’s ripe for exploring. Wherever you go, Peru’s vibrant Andean culture, one of the most exciting in the Americas, will brighten your travels: tucked-away highland towns explode into colour on market day, and local fiestas are celebrated with unbridled enthusiasm.")
        locations.append(peru)
        
        let new_zealand = Location(name: "New Zealand", image: #imageLiteral(resourceName: "new_zealand"), description: "Kiwis – the people, not the emblematic flightless bird – can’t believe their luck at being born in what they call “Godzone” (God’s own country). Year after year, travellers list New Zealand in the top ten of places they’d like to visit – and you never meet anyone who has been and didn’t love the place. And what’s not to like? With craggy coastlines, sweeping beaches, primeval forests, snowcapped mountains and impressive geysers, the scenery is truly majestic. The forests come inhabited by strange birds that have evolved to fill evolutionary niches normally occupied by mammals, while penguins, whales and seals ring the coast. Maori have only been here for 800 years but retain distinct and fascinating customs overlaid by colonial European and increasingly Asian cultures that together create a vibrant, if understated, urban life.")
        locations.append(new_zealand)
        
        let mexico = Location(name: "Mexico", image: #imageLiteral(resourceName: "mexico"), description: "The home of tacos, Aztecs, sombreros and tequila – not to mention Pancho Villa, Salma Hayek and Frida Kahlo – almost everyone on the planet knows something about Mexico. Yet there’s a lot more to this country beyond the stereotypes. One of the world’s great civilizations, Mexico offers a tantalizing blend of Mesoamerican cultures, Spanish traditions and contemporary arts. Its landscapes range from the shimmering blue coastline of Baja California and the iconic cactus-strewn deserts of the north, to the Maya villages and gorgeous palm-smothered beaches of the south. You can climb volcanoes, watch whales and tour agave farms. And sprinkled throughout you’ll find richly adorned colonial churches, giant pyramids and a sophisticated cuisine.")
        locations.append(mexico)
        
        let thailand = Location(name: "Thailand", image: #imageLiteral(resourceName: "thailand"), description: "With sixteen million foreigners flying into the country each year, Thailand is Asia’s primary travel destination and offers a host of places to visit. Yet despite this vast influx of visitors, Thailand’s cultural integrity remains largely undamaged – a country that adroitly avoided colonization has been able to absorb Western influences while maintaining its own rich heritage. Though the high-rises and neon lights occupy the foreground of the tourist picture, the typical Thai community is still the farming village, and you need not venture far to encounter a more traditional scene of fishing communities, rubber plantations and Buddhist temples. Around forty percent of Thais earn their living from the land, based around the staple rice, which forms the foundation of the country’s unique and famously sophisticated cuisine.")
        locations.append(thailand)
        
        let usa = Location(name: "USA", image: #imageLiteral(resourceName: "usa"), description: "As the world’s only superpower and biggest economy by a huge margin, almost everyone on the planet knows something about the USA, even if they’ve never been. The Statue of Liberty, the Empire State, the Hollywood sign, Las Vegas neon, Golden Gate and the White House have long been global icons, and American brands and images are familiar everywhere, from Apple computers and Levi’s to Coca-Cola and hot dogs. Yet first-time visitors should expect some surprises. Though its cities draw the most tourists – New York, New Orleans, Miami, Los Angeles and San Francisco are all incredible destinations in their own right – America is above all a land of stunningly diverse and achingly beautiful landscapes. In one nation you have the mighty Rockies and spectacular Cascades, the vast, mythic desert landscapes of the Southwest, the endless, rolling plains of Texas and Kansas, the tropical beaches and Everglades of Florida, the giant redwoods of California and the sleepy, pristine villages of New England. You can soak up the mesmerizing vistas in Crater Lake, Yellowstone and Yosemite national parks, stand in awe at the Grand Canyon, hike the Black Hills, cruise the Great Lakes, paddle in the Mississippi, surf the gnarly breaks of Oahu and get lost in the vast wilderness of Alaska. Or you could easily plan a trip that focuses on the out-of-the-way hamlets, remote prairies, eerie ghost towns and forgotten byways that are every bit as “American” as its showpiece icons and monuments.")
        locations.append(usa)
    }
    
    func getLocations()->[Location] {
        return locations
    }
}
